[package]
name = "bls_test"
version = "0.1.0"
authors = ["rink1969 <rink1969@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls-signatures = "0.2.0"
rand = "=0.4.6"